INSERT INTO topics (id, name, description, icon)
VALUES
  ('docker', 'Docker', 'Container basics', 'DK'),
  ('pipelines', 'Pipelines', 'CI/CD basics', 'PL'),
  ('terraform', 'Terraform', 'Infrastructure as Code basics', 'TF'),
  ('git', 'Git', 'Version control basics', 'GT')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon;

INSERT INTO questions (topic_id, question_text, options, correct_index)
VALUES
  ('docker', 'What is Docker?', '["A programming language", "A containerization platform", "A database", "An operating system"]'::jsonb, 1),
  ('docker', 'What is a Docker container?', '["A virtual machine", "A lightweight, isolated runtime for applications", "A network protocol", "A storage device"]'::jsonb, 1),
  ('docker', 'What is a Docker image?', '["A running container", "A template to create containers", "A log file", "A database backup"]'::jsonb, 1),
  ('docker', 'Which command builds a Docker image?', '["docker run", "docker build", "docker start", "docker exec"]'::jsonb, 1),
  ('docker', 'Which file defines how to build a Docker image?', '["docker.yaml", "Dockerfile", "compose.json", "image.txt"]'::jsonb, 1),
  ('docker', 'Which command runs a container?', '["docker build", "docker run", "docker stop", "docker rm"]'::jsonb, 1),
  ('docker', 'What does docker pull do?', '["Deletes an image", "Downloads an image from a registry", "Runs a container", "Builds an image"]'::jsonb, 1),
  ('docker', 'What does docker push do?', '["Uploads an image to a registry", "Starts a container", "Stops a container", "Builds an image"]'::jsonb, 0),
  ('docker', 'What is Docker Hub?', '["A local tool", "A public image registry", "A CLI command", "A container runtime"]'::jsonb, 1),
  ('docker', 'What does docker ps show?', '["Images", "Running containers", "Volumes", "Networks"]'::jsonb, 1),
  ('docker', 'What does docker stop do?', '["Deletes a container", "Stops a running container", "Builds an image", "Creates a container"]'::jsonb, 1),
  ('docker', 'What is a Docker volume?', '["A network", "Persistent data storage", "A container image", "A log file"]'::jsonb, 1),
  ('docker', 'What is Docker Compose used for?', '["Managing multiple containers", "Building kernels", "Writing code", "Managing users"]'::jsonb, 0),
  ('docker', 'Which file is used by Docker Compose?', '["compose.yaml", "Dockerfile", "build.txt", "config.ini"]'::jsonb, 0),
  ('docker', 'What does docker logs do?', '["Shows container logs", "Builds images", "Deletes logs", "Creates volumes"]'::jsonb, 0),
  ('docker', 'What does docker rm do?', '["Runs a container", "Removes a container", "Builds an image", "Starts a container"]'::jsonb, 1),
  ('docker', 'What is port mapping in Docker?', '["Connecting containers to databases", "Mapping container ports to host ports", "Creating volumes", "Running multiple containers"]'::jsonb, 1),
  ('docker', 'What does docker exec do?', '["Runs commands inside a container", "Builds images", "Stops containers", "Pushes images"]'::jsonb, 0),
  ('docker', 'What is a container registry?', '["A log viewer", "A storage for Docker images", "A container runtime", "A CLI tool"]'::jsonb, 1),
  ('docker', 'What does docker images list?', '["Running containers", "Available images", "Volumes", "Networks"]'::jsonb, 1),
  ('pipelines', 'What is a CI/CD pipeline?', '["A database", "An automated workflow for building and deploying code", "A programming language", "A server"]'::jsonb, 1),
  ('pipelines', 'What does CI stand for?', '["Code Integration", "Continuous Integration", "Central Infrastructure", "Cloud Interface"]'::jsonb, 1),
  ('pipelines', 'What does CD stand for?', '["Code Deployment", "Continuous Delivery/Deployment", "Cloud Development", "Central Database"]'::jsonb, 1),
  ('pipelines', 'What is a pipeline stage?', '["A hardware component", "A step in a pipeline", "A programming language", "A server"]'::jsonb, 1),
  ('pipelines', 'What triggers a pipeline?', '["A database query", "A code commit", "A UI click only", "A server reboot"]'::jsonb, 1),
  ('pipelines', 'What is a build step?', '["Writing code", "Compiling or packaging code", "Deploying apps", "Monitoring logs"]'::jsonb, 1),
  ('pipelines', 'What is automated testing in pipelines?', '["Manual QA", "Running tests automatically", "Deploying apps", "Writing code"]'::jsonb, 1),
  ('pipelines', 'What is an artifact?', '["A log file", "A build output", "A container", "A test case"]'::jsonb, 1),
  ('pipelines', 'What is deployment in CD?', '["Writing code", "Releasing software to environments", "Testing code", "Building images"]'::jsonb, 1),
  ('pipelines', 'What is a pipeline failure?', '["Successful deployment", "A step that fails", "A database issue only", "A network cable issue"]'::jsonb, 1),
  ('pipelines', 'What is a pipeline log?', '["Source code", "Execution output of pipeline steps", "A config file", "A database"]'::jsonb, 1),
  ('pipelines', 'What is a pipeline agent/runner?', '["A UI tool", "A machine executing pipeline jobs", "A database", "A network device"]'::jsonb, 1),
  ('pipelines', 'What is version control integration?', '["Manual file copying", "Connecting pipelines to Git repositories", "Monitoring logs", "Running servers"]'::jsonb, 1),
  ('pipelines', 'What is a pipeline configuration file?', '["Source code", "File defining pipeline steps", "Log file", "Binary file"]'::jsonb, 1),
  ('pipelines', 'What is rollback?', '["Moving forward", "Reverting to a previous version", "Building code", "Testing code"]'::jsonb, 1),
  ('pipelines', 'What is a manual approval step?', '["Automatic deployment", "Human approval before continuing", "Code compilation", "Log monitoring"]'::jsonb, 1),
  ('pipelines', 'What is a test stage?', '["Deployment step", "Running tests", "Building images", "Writing code"]'::jsonb, 1),
  ('pipelines', 'What is a deploy stage?', '["Testing code", "Releasing software", "Writing code", "Debugging"]'::jsonb, 1),
  ('pipelines', 'What is a pipeline variable?', '["A log file", "A configurable value used in pipelines", "A container", "A database"]'::jsonb, 1),
  ('pipelines', 'What is pipeline caching?', '["Deleting files", "Reusing data to speed up builds", "Deploying apps", "Testing code"]'::jsonb, 1),
  ('terraform', 'What is Terraform?', '["A programming language", "An Infrastructure as Code tool", "A database", "A container runtime"]'::jsonb, 1),
  ('terraform', 'What language does Terraform use?', '["Python", "HCL", "Java", "C#"]'::jsonb, 1),
  ('terraform', 'What is a Terraform provider?', '["A database", "A plugin for APIs", "A container", "A log file"]'::jsonb, 1),
  ('terraform', 'What does terraform init do?', '["Deletes resources", "Initializes the project", "Applies changes", "Runs tests"]'::jsonb, 1),
  ('terraform', 'What does terraform plan do?', '["Applies changes", "Shows planned changes", "Deletes resources", "Builds containers"]'::jsonb, 1),
  ('terraform', 'What does terraform apply do?', '["Shows plan", "Applies infrastructure changes", "Deletes files", "Runs tests"]'::jsonb, 1),
  ('terraform', 'What is a resource in Terraform?', '["A log file", "An infrastructure component", "A container", "A test case"]'::jsonb, 1),
  ('terraform', 'What is a state file?', '["A config file", "Tracks infrastructure state", "A log file", "A script"]'::jsonb, 1),
  ('terraform', 'What is terraform destroy?', '["Creates resources", "Deletes managed infrastructure", "Runs tests", "Builds code"]'::jsonb, 1),
  ('terraform', 'What is a module?', '["A log file", "Reusable Terraform code", "A container", "A database"]'::jsonb, 1),
  ('terraform', 'What is a variable?', '["A log file", "Input value for configs", "A resource", "A provider"]'::jsonb, 1),
  ('terraform', 'What is an output?', '["A log file", "Returned value after apply", "A variable", "A provider"]'::jsonb, 1),
  ('terraform', 'What is remote state?', '["Local file", "State stored remotely", "A container", "A test"]'::jsonb, 1),
  ('terraform', 'What is terraform fmt?', '["Deletes code", "Formats code", "Applies changes", "Runs tests"]'::jsonb, 1),
  ('terraform', 'What is terraform validate?', '["Runs code", "Checks configuration", "Deletes resources", "Builds images"]'::jsonb, 1),
  ('terraform', 'What is drift?', '["Planned change", "Difference between actual and desired state", "A test", "A variable"]'::jsonb, 1),
  ('terraform', 'What is a backend?', '["A UI", "State storage configuration", "A container", "A script"]'::jsonb, 1),
  ('terraform', 'What is interpolation?', '["Deleting values", "Using variables in strings", "Running tests", "Deploying code"]'::jsonb, 1),
  ('terraform', 'What is a data source?', '["Creates resources", "Reads existing infrastructure", "Deletes resources", "Builds code"]'::jsonb, 1),
  ('terraform', 'What is idempotency?', '["Running once only", "Same result on repeated runs", "Deleting resources", "Testing code"]'::jsonb, 1),
  ('git', 'What is Git?', '["A database", "A version control system", "A programming language", "A container tool"]'::jsonb, 1),
  ('git', 'What does git clone do?', '["Deletes repo", "Copies a repository", "Commits changes", "Pushes code"]'::jsonb, 1),
  ('git', 'What does git add do?', '["Deletes files", "Stages changes", "Pushes code", "Pulls code"]'::jsonb, 1),
  ('git', 'What does git commit do?', '["Uploads code", "Saves changes locally", "Deletes repo", "Builds code"]'::jsonb, 1),
  ('git', 'What does git push do?', '["Downloads code", "Uploads commits", "Deletes commits", "Runs tests"]'::jsonb, 1),
  ('git', 'What does git pull do?', '["Uploads code", "Fetches and merges changes", "Deletes repo", "Builds code"]'::jsonb, 1),
  ('git', 'What is a branch?', '["A file", "A separate line of development", "A server", "A log"]'::jsonb, 1),
  ('git', 'What does git checkout do?', '["Deletes branch", "Switches branches", "Pushes code", "Runs tests"]'::jsonb, 1),
  ('git', 'What is merge?', '["Deleting code", "Combining branches", "Running tests", "Building code"]'::jsonb, 1),
  ('git', 'What is a conflict?', '["Successful merge", "Conflicting changes", "A log file", "A test"]'::jsonb, 1),
  ('git', 'What does git status show?', '["Logs", "Repo state", "Branches only", "Commits only"]'::jsonb, 1),
  ('git', 'What does git log show?', '["Files", "Commit history", "Branches", "Config"]'::jsonb, 1),
  ('git', 'What is a repository?', '["A server", "A project with history", "A file", "A container"]'::jsonb, 1),
  ('git', 'What is origin?', '["A branch", "Default remote name", "A file", "A commit"]'::jsonb, 1),
  ('git', 'What is staging area?', '["Final repo", "Area for preparing commits", "A branch", "A log"]'::jsonb, 1),
  ('git', 'What is HEAD?', '["A file", "Current commit reference", "A branch", "A log"]'::jsonb, 1),
  ('git', 'What does git diff show?', '["Logs", "Changes", "Branches", "Commits"]'::jsonb, 1),
  ('git', 'What is a tag?', '["A branch", "A labeled commit", "A file", "A log"]'::jsonb, 1),
  ('git', 'What is rebase?', '["Deleting commits", "Rewriting commit history", "Running tests", "Building code"]'::jsonb, 1),
  ('git', 'What is fork?', '["Deleting repo", "Copying repo to own account", "Running tests", "Building code"]'::jsonb, 1)
ON CONFLICT DO NOTHING;
